version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    ports:
      - "8491:8491"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - BASE_URL=${BASE_URL:-https://handbook.gitlab.com/}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8491}
    volumes:
      # Mount logs directory to persist logs
      - ./logs:/app/logs
      # Mount qdrant_data directory to persist vector database
      - ./qdrant_data:/app/qdrant_data
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 