services:
  chromadb:
    image: chromadb/chroma
    volumes:
      - chromadb_data:/chroma/chroma
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_NO_COPY_WARNING=TRUE
      - ALLOW_RESET=TRUE

volumes:
  chromadb_data: 