version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    ports:
      - "8491:8491"
    environment:
      - HOST=0.0.0.0
      - PORT=8491
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - BASE_URL=${BASE_URL:-https://handbook.gitlab.com/}
      - LARK_APP_ID=${LARK_APP_ID:-}
      - LARK_APP_SECRET=${LARK_APP_SECRET:-}
      - LARK_VERIFICATION_TOKEN=${LARK_VERIFICATION_TOKEN:-}
      - LARK_ENCRYPT_KEY=${LARK_ENCRYPT_KEY:-}
      - LARK_HOST=${LARK_HOST:-https://open.feishu.cn}
    volumes:
      # Mount logs directory to persist logs
      - ./logs:/app/logs
      # Mount qdrant_data directory to persist vector database
      - ./qdrant_data:/app/qdrant_data
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 